# Generated by Django 3.2.19 on 2025-01-06 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Chef', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DishApi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dish_name', models.CharField(max_length=20)),
                ('rating', models.IntegerField()),
                ('chef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Chef.chefapi')),
            ],
        ),
    ]
