# Generated by Django 3.2.19 on 2025-01-10 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restapi',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='auhtor_image/'),
        ),
    ]
