# Generated by Django 3.2.19 on 2025-01-06 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Chef', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chefapi',
            name='image_of_chef',
        ),
    ]
